name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: BileMo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, pdo_mysql
        ini-values: post_max_size=256M, max_execution_time=300
        coverage: none
        tools: composer

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Copy .env file
      run: cp .env .env.local

    - name: Set database URL
      run: echo "DATABASE_URL=mysql://BileMo:BileMo@127.0.0.1:3306/BileMo?serverVersion=5.7&charset=utf8mb4" >> .env.local

    - name: Run database migrations
      run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

    - name: Load fixtures
      run: php bin/console doctrine:fixtures:load --env=test --no-interaction

    - name: Run tests
      run: ./vendor/bin/phpunit

    - name: Cache API Platform metadata
      run: php bin/console cache:warmup

    - name: Test API Platform
      run: php bin/console api:query --env=test
