name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: BileMo
          MYSQL_USER: BileMo
          MYSQL_PASSWORD: BileMo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl, pdo_mysql, curl
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=1G
        coverage: none
        tools: composer, symfony-cli

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Run database migrations
      run: php bin/console doctrine:migrations:migrate --no-interaction

    - name: Load Fixtures
      run: php bin/console doctrine:fixtures:load --no-interaction

    - name: Run tests
      run: vendor/bin/phpunit --testdox
